// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAIWkm5j1Mi8cuDj-Wh_et-vpcuL1f9Yk',
    appId: '1:1017582329798:web:77625686925b6b141edcc7',
    messagingSenderId: '1017582329798',
    projectId: 'l2-transition',
    authDomain: 'l2-transition.firebaseapp.com',
    storageBucket: 'l2-transition.appspot.com',
    measurementId: 'G-FNWS884P60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3KfTPc8iNccnInHTSfK52utaw5HuI4hY',
    appId: '1:1017582329798:android:38ab812c354e23cc1edcc7',
    messagingSenderId: '1017582329798',
    projectId: 'l2-transition',
    storageBucket: 'l2-transition.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTRdDI_YU58TEqFEzb_JibwKROijWt22o',
    appId: '1:1017582329798:ios:93f95c69fd0f4a181edcc7',
    messagingSenderId: '1017582329798',
    projectId: 'l2-transition',
    storageBucket: 'l2-transition.appspot.com',
    iosClientId: '1017582329798-0t93lpfnehp030l6rhqf05uli13sss8q.apps.googleusercontent.com',
    iosBundleId: 'com.uofg.l2transition.l2Transition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTRdDI_YU58TEqFEzb_JibwKROijWt22o',
    appId: '1:1017582329798:ios:93f95c69fd0f4a181edcc7',
    messagingSenderId: '1017582329798',
    projectId: 'l2-transition',
    storageBucket: 'l2-transition.appspot.com',
    iosClientId: '1017582329798-0t93lpfnehp030l6rhqf05uli13sss8q.apps.googleusercontent.com',
    iosBundleId: 'com.uofg.l2transition.l2Transition',
  );
}
